spring:
  application:
    name: user-services
  config:
    import: optional:configserver:http://localhost:8098/
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  jwtSecret: "9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9"
  jwtExpirationMS: 7200000
#   jwtCookieName: cmdm

logging:
  level:
    org:
      springframework:
        security: DEBUG

rabbitmq:
  email:
    queue: email.queue

paystack:
  base-url: https://api.paystack.co
  secret-key: ${PAYSTACK_SECRET}


